Don't install @github/local-action or its myriad dependencies [dependabot skip]
This does remove the transitive requirement for tslib from our dev
dependencies, which makes rollup break with:

    RollupError: [plugin typescript] @rollup/plugin-typescript: Could not find
    module 'tslib', which is required by this plugin. Is it installed?

Add tslib explicitly to our dev dependencies, so it's installed when the build
pipeline recompiles to check the state of `dist/`.